version: '2.4'
services:
    api:
      build: .
      volumes:
        - .:/var/task
      working_dir: /var/task
      environment:
        - HOME=/tmp
      entrypoint: ["poetry", "run"]
      user: "${COMPOSE_UID:-1000}:${COMPOSE_GID:-1000}"
      command: ["uvicorn", "main:app", "--reload", "--host=0.0.0.0"]
      ports:
        - 8000:8000
      depends_on:
        - db

    db:
      image: mysql:5.7
      ports:
        - 3306:3306
      volumes:
        - ./db1:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=phamphong9981
        - MYSQL_DATABASE=phamphong
        - MYSQL_USER=phamphong9981
        - MYSQL_PASSWORD=phamphong9981